name: 'SPBuild'
description: 'ScorePlay tooling for GoLang repositories'
inputs:
  working-directory:
    description: 'Working directory'
    required: false
    default: '.'
outputs:
  packages:
    description: 'List of modified packages'
  services:
    description: 'List of services that needs to be rebuilt'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.working-directory }}
