name: 'SPBuild'
description: 'ScorePlay tooling for GoLang repositories'
outputs:
  packages:
    description: 'List of modified packages'
  services:
    description: 'List of services that needs to be rebuilt'
runs:
  using: 'docker'
  image: 'Dockerfile'
