name: 'SPBuild'
description: 'ScorePlay tooling for GoLang repositories'
inputs:
  go-mod-dir:
    description: 'Path to the directory containing the go.mod file (defaults to repository root)'
    required: false
outputs:
  packages:
    description: 'List of modified packages'
  services:
    description: 'List of services that needs to be rebuilt'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - {{ inputs.go-mod-dir }}
